---
homebrew_installed_packages:
  - git
  - gh
  - kubectl
  - minikube
  - nmap
  - node
  - openssl
  - skaffold
  - wget

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - cursor
  - docker
  - dropbox
  - google-chrome
  - slack
