---
- name: Configure Mac
  hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']

  pre_tasks:
    - name: Include override playbook config.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
